name: Docker CI

on: 
  push: 
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out the repo
        uses: actions/checkout@v3
      - name: Docker Login and setup
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
      - name: Building the image
        run: docker build -t ${{secrets.DOCKER_USERNAME}}/flask:latest .
      - name: pushing the image
        run: docker push ${{secrets.DOCKER_USERNAME}}/flask:latest